from pydantic import Field
from pydantic_settings import BaseSettings


class CacheSettings(BaseSettings):
    CACHE_ENABLED: bool = Field(
        default=True,
        description="Enable Redis cache. Set to False to disable caching.",
    )
    CACHE_HOST: str = Field(
        default="localhost",
        description="Redis cache host",
    )
    CACHE_PORT: int = Field(
        default=6379,
        ge=1,
        le=65535,
        description="Redis cache port",
    )
    CACHE_PASSWORD: str | None = Field(
        default=None,
        description="Redis cache password (optional)",
    )
    CACHE_DB: int = Field(
        default=0,
        ge=0,
        le=15,
        description="Redis database number (0-15)",
    )
    CACHE_SOCKET_TIMEOUT: int = Field(
        default=5,
        ge=1,
        description="Socket timeout in seconds for Redis operations",
    )
    CACHE_SOCKET_CONNECT_TIMEOUT: int = Field(
        default=5,
        ge=1,
        description="Socket connection timeout in seconds",
    )
    CACHE_MAX_CONNECTIONS: int = Field(
        default=50,
        ge=1,
        description="Maximum number of connections in the Redis connection pool",
    )
    CACHE_RETRY_ON_TIMEOUT: bool = Field(
        default=True,
        description="Retry operations on timeout",
    )
    CACHE_DEFAULT_TTL: int = Field(
        default=300,
        ge=1,
        description="Default TTL for cached responses in seconds (used by @cached() decorator)",
    )
    CACHE_KEY_PREFIX: str = Field(
        default="fastapi-cache",
        description="Prefix for cache keys generated by fastapi-cache2",
    )
    CACHE_MIDDLEWARE_ENABLED: bool = Field(
        default=True,
        description="Enable HTTP response caching middleware. Automatically caches GET requests.",
    )
    CACHE_MIDDLEWARE_TTL: int = Field(
        default=300,
        ge=1,
        description="Default TTL for cached HTTP responses in seconds",
    )
    CACHE_MIDDLEWARE_EXCLUDE_PATHS: list[str] = Field(
        default_factory=lambda: ["/api/docs", "/api/redoc", "/api/openapi.json", "/api/v1/health"],
        description="List of URL paths to exclude from caching (e.g., health checks, docs)",
    )
    CACHE_MIDDLEWARE_KEY_PREFIX: str = Field(
        default="http_cache",
        description="Prefix for cache keys generated by the middleware",
    )

    CACHE_SENSITIVE_HEADERS: set[str] = {
        "authorization",
        "cookie",
        "set-cookie",
        "x-api-key",
        "x-auth-token",
        "x-csrf-token",
        "x-request-id",
        "x-trace-id",
    }
    CACHE_REQUIRED_FIELDS: set[str] = {"status_code", "headers", "body"}

    CACHE_MIN_TTL: int = 1
    CACHE_MAX_TTL: int = 2147483647

    @property
    def cache_url(self: "CacheSettings") -> str:
        if self.CACHE_PASSWORD:
            return f"redis://:{self.CACHE_PASSWORD}@{self.CACHE_HOST}:{self.CACHE_PORT}/{self.CACHE_DB}"
        return f"redis://{self.CACHE_HOST}:{self.CACHE_PORT}/{self.CACHE_DB}"
